version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.base
      target: backend
    command: yarn backend:dev:docker
    volumes:
      - ./apps/backend:/app/apps/backend
      - /app/apps/backend/node_modules
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - api_network

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.base
      target: frontend
    command: yarn frontend:dev:docker
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: nestjs
      POSTGRES_PASSWORD: nestjs
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - api_network

volumes:
  docker-nest-postgres:

networks:
  api_network: