###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:18-alpine AS backend

WORKDIR /app
RUN apk add python3 alpine-sdk
RUN yarn global add turbo
COPY . .
RUN yarn install
RUN yarn workspace backend prisma generate
RUN yarn turbo run build --filter=backend

FROM node:18-alpine AS frontend
WORKDIR /app
COPY --from=backend /app /app
RUN yarn turbo run build --filter=frontend
